PRODUCT_NAME=xctidy

# `test`'s recipe needs `set -o pipefail` (POSIX dash doesn't support it) --
# harmless to pin here since this project is macOS-only anyway (see
# .github/workflows/makefile.yml: XCTest parsing only ever runs against a
# real Xcode/macOS build).
SHELL:=/bin/bash

PREFIX?=/usr/local

CP=/bin/cp -f
MKDIR=/bin/mkdir -p
RM=/bin/rm -f
SWIFT?=swift
SWIFTLINT?=swiftlint

# Ask for sudo password when the target isn't writable
SUDO:=$(shell d="$(PREFIX)/bin"; while [ ! -d "$$d" ] && [ "$$d" != "/" ]; do d=$$(dirname "$$d"); done; test -w "$$d" && echo "" || echo "sudo")

SWIFT_BUILD_FLAGS=--configuration release

# Baked into the binary for `xctidy --version` (see Sources/xctidy/main.swift).
# Derived from the nearest git tag so the release process stays just "tag and
# push" (docs/DEVELOPMENT.md "Cutting a release") -- no separate version
# constant to remember to bump in lockstep with the tag. Strips the leading
# "v" to match xcbeautify's bare "3.2.1" --version style. --always falls back
# to an abbreviated commit hash if no tag is reachable at all; --dirty flags
# a build made with uncommitted changes. Outside a git checkout (or before
# the first tag existed), git describe fails silently and VERSION is empty --
# the ifeq below catches that and falls back to "dev".
VERSION:=$(shell git describe --tags --always --dirty 2>/dev/null | sed 's/^v//')
ifeq ($(VERSION),)
VERSION:=dev
endif

.PHONY: all
all: build

.PHONY: version
version:
	@echo "// Generated by \`make version\` -- do not hand-edit, do not commit" > Sources/xctidy/Version.swift
	@echo "// changes (see Makefile). Committed placeholder value is \"dev\"." >> Sources/xctidy/Version.swift
	@echo "let xctidyVersion = \"$(VERSION)\"" >> Sources/xctidy/Version.swift

.PHONY: build
build: version
	$(SWIFT) build $(SWIFT_BUILD_FLAGS)

.PHONY: test
test:
	$(SWIFT) build --product $(PRODUCT_NAME)
	set -o pipefail; $(SWIFT) test 2>&1 | "$$($(SWIFT) build --show-bin-path)/$(PRODUCT_NAME)" Tests/XctidyKitTests

.PHONY: lint
lint:
	$(SWIFTLINT) lint --strict

.PHONY: install
install: build
	$(eval BINARY_DIRECTORY := $(PREFIX)/bin)
	$(eval BUILD_DIRECTORY := $(shell $(SWIFT) build --show-bin-path $(SWIFT_BUILD_FLAGS)))
	$(SUDO) $(MKDIR) $(BINARY_DIRECTORY)
	$(SUDO) $(CP) "$(BUILD_DIRECTORY)/$(PRODUCT_NAME)" "$(BINARY_DIRECTORY)"

.PHONY: uninstall
uninstall:
	$(SUDO) $(RM) "$(PREFIX)/bin/$(PRODUCT_NAME)"

.PHONY: clean
clean:
	$(SWIFT) package clean

.PHONY: xcode
xcode: version
	open Package.swift

.PHONY: check
check:
	@LOG=$$(mktemp); \
  if $(SWIFT) test > "$$LOG" 2>&1; then \
    echo "PASS"; \
  else \
    cat "$$LOG"; \
    rm -f "$$LOG"; \
    exit 1; \
  fi; \
  rm -f "$$LOG"
